using System.Text;

namespace BuffSystem.Editor.AuthoringGraphs
{
    /// <summary>
    /// 将 CompositeEffect 计划输出为 Effect 草稿源码文本。
    /// 该 Emitter 只生成字符串，不写 .cs 文件，不修改 registry，不创建 BuffConfigData。
    /// </summary>
    internal static class BuffGraphCompositeEffectEmitter
    {
        internal static bool TryEmit(
            BuffGraphCompositeEffectPlan plan,
            out string code,
            out string error)
        {
            code = string.Empty;
            error = string.Empty;

            if (plan == null)
            {
                error = "CompositeEffect plan 为空。";
                return false;
            }

            plan.GeneratedActionFieldCount = 0;
            plan.GeneratedActionExecuteCallCount = 0;

            if (plan.HasErrors)
            {
                error = string.Join("\n", plan.Errors);
                return false;
            }

            if (string.IsNullOrWhiteSpace(plan.CompositeEffectClassName))
            {
                AddUniqueError(plan, "CompositeEffectClassName 为空，无法生成代码文本。");
                error = string.Join("\n", plan.Errors);
                return false;
            }

            if (string.IsNullOrWhiteSpace(plan.Namespace))
            {
                AddUniqueError(plan, "CompositeEffect namespace 为空，无法生成代码文本。");
                error = string.Join("\n", plan.Errors);
                return false;
            }

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("using BuffSystem;");
            builder.AppendLine();
            builder.AppendLine($"namespace {plan.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {BuildClassSummary(plan)}");
            builder.AppendLine("    /// Generated by Buff Authoring Hub from BuffCandidateGraph CompositeEffect plan.");
            builder.AppendLine("    /// Note: only register the CompositeEffectId, not child EffectNode ids.");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public sealed class {plan.CompositeEffectClassName} : BuffEffectExecutorBase");
            builder.AppendLine("    {");
            builder.AppendLine($"        internal const int EffectId = {plan.CompositeEffectId};");

            for (int i = 0; i < plan.FieldPlans.Count; i++)
            {
                BuffGraphEffectFieldPlan field = plan.FieldPlans[i];
                builder.AppendLine($"        private readonly {field.ActionTypeName} {field.ActionVariableName} = new {field.ActionTypeName}();");
                plan.GeneratedActionFieldCount++;
            }

            for (int i = 0; i < plan.LifecyclePlans.Count; i++)
                AppendLifecycle(builder, plan, plan.LifecyclePlans[i]);

            builder.AppendLine("    }");
            builder.AppendLine("}");

            ValidateGeneratedCallCompleteness(plan);
            if (plan.HasErrors)
            {
                error = string.Join("\n", plan.Errors);
                return false;
            }

            code = builder.ToString();
            return true;
        }

        private static void AppendLifecycle(StringBuilder builder, BuffGraphCompositeEffectPlan plan, BuffGraphCompositeLifecyclePlan lifecycle)
        {
            if (lifecycle.Actions.Count == 0 && lifecycle.Todos.Count == 0)
                return;

            builder.AppendLine();
            if (lifecycle.IsStackChanged)
                builder.AppendLine("        public override void OnStackChanged(in BuffEffectContext context, int delta)");
            else
                builder.AppendLine($"        public override void {lifecycle.LifecycleName}(in BuffEffectContext context)");

            builder.AppendLine("        {");
            if (lifecycle.IsStackChanged && lifecycle.Actions.Count > 0)
                builder.AppendLine("            // IBuffGraphAction 第一版不接收 delta；如需 delta，请后续扩展专用接口。");

            for (int i = 0; i < lifecycle.Todos.Count; i++)
                builder.AppendLine("            " + lifecycle.Todos[i]);

            for (int i = 0; i < lifecycle.Actions.Count; i++)
            {
                builder.AppendLine($"            {lifecycle.Actions[i].ActionVariableName}.Execute(in context);");
                plan.GeneratedActionExecuteCallCount++;
            }

            builder.AppendLine("        }");
        }

        private static void ValidateGeneratedCallCompleteness(BuffGraphCompositeEffectPlan plan)
        {
            if (plan.ExpectedActionCallCount > 0 && plan.GeneratedActionExecuteCallCount == 0)
                AddUniqueError(plan, "CompositeEffect codegen expected Action calls, but generated no Execute(in context) calls.");

            if (plan.ExpectedActionCallCount != plan.GeneratedActionExecuteCallCount)
                AddUniqueError(plan, $"CompositeEffect codegen Action call count mismatch: expected={plan.ExpectedActionCallCount}, generated={plan.GeneratedActionExecuteCallCount}.");

            if (plan.ExpectedActionCallCount > 0 && plan.GeneratedActionFieldCount == 0)
                AddUniqueError(plan, "CompositeEffect codegen expected Action fields, but generated no readonly action fields.");
        }

        private static string BuildClassSummary(BuffGraphCompositeEffectPlan plan)
        {
            if (!string.IsNullOrWhiteSpace(plan.CompositeEffectName))
                return plan.CompositeEffectName;

            if (!string.IsNullOrWhiteSpace(plan.BuffName))
                return plan.BuffName + " CompositeEffect";

            return "CompositeEffect generated from BuffCandidateGraph.";
        }

        private static void AddUniqueError(BuffGraphCompositeEffectPlan plan, string message)
        {
            if (!plan.Errors.Contains(message))
                plan.Errors.Add(message);
        }
    }
}
