using System.Text;

namespace BuffSystem.Editor.AuthoringGraphs
{
    /// <summary>
    /// 将 Graph Effect 调用链计划输出为 Effect 草稿源码。
    /// 只负责字符串生成，不写文件，不修改 registry，不进入 runtime。
    /// </summary>
    internal static class BuffGraphEffectCodegenEmitter
    {
        internal static string Emit(BuffGraphEffectCodegenPlan plan, string classSummary)
        {
            plan.GeneratedActionFieldCount = 0;
            plan.GeneratedActionExecuteCallCount = 0;

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("using BuffSystem;");
            builder.AppendLine();
            builder.AppendLine($"namespace {plan.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {classSummary}");
            builder.AppendLine("    /// Generated by Buff Authoring Hub from BuffCandidateGraph.");
            builder.AppendLine("    /// Note: manually register this effect in BuffEffectRegistryBootstrap before production use.");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    internal sealed class {plan.EffectClassName} : BuffEffectExecutorBase");
            builder.AppendLine("    {");
            builder.AppendLine($"        internal const int EffectId = {plan.EffectId};");

            for (int i = 0; i < plan.FieldPlans.Count; i++)
            {
                BuffGraphEffectFieldPlan field = plan.FieldPlans[i];
                builder.AppendLine($"        private readonly {field.ActionTypeName} {field.ActionVariableName} = new {field.ActionTypeName}();");
                plan.GeneratedActionFieldCount++;
            }

            for (int i = 0; i < plan.LifecyclePlans.Count; i++)
                AppendLifecycle(builder, plan.LifecyclePlans[i]);

            builder.AppendLine("    }");
            builder.AppendLine("}");
            ValidateGeneratedCallCompleteness(plan);
            return builder.ToString();
        }

        private static void AppendLifecycle(StringBuilder builder, BuffGraphEffectLifecyclePlan lifecycle)
        {
            builder.AppendLine();
            if (lifecycle.IsStackChanged)
                builder.AppendLine("        public override void OnStackChanged(in BuffEffectContext context, int delta)");
            else
                builder.AppendLine($"        public override void {lifecycle.LifecycleName}(in BuffEffectContext context)");

            builder.AppendLine("        {");
            if (lifecycle.IsStackChanged && lifecycle.Actions.Count > 0)
                builder.AppendLine("            // 第一版 IBuffGraphAction 不接收 delta；如需 delta，请后续扩展 IBuffGraphStackChangedAction。");

            for (int i = 0; i < lifecycle.Todos.Count; i++)
                builder.AppendLine("            " + lifecycle.Todos[i]);

            if (lifecycle.Actions.Count == 0 && lifecycle.Todos.Count == 0)
                AppendDefaultTodo(builder, lifecycle);

            for (int i = 0; i < lifecycle.Actions.Count; i++)
            {
                builder.AppendLine($"            {lifecycle.Actions[i].ActionVariableName}.Execute(in context);");
            }

            builder.AppendLine("        }");
        }

        private static void ValidateGeneratedCallCompleteness(BuffGraphEffectCodegenPlan plan)
        {
            int executeCount = 0;
            for (int i = 0; i < plan.LifecyclePlans.Count; i++)
                executeCount += plan.LifecyclePlans[i].Actions.Count;

            plan.GeneratedActionExecuteCallCount = executeCount;

            if (plan.ExpectedActionCallCount > 0 && plan.GeneratedActionExecuteCallCount == 0)
                AddUniqueError(plan, "Graph Effect codegen expected Action calls, but generated no Execute(in context) calls.");

            if (plan.ExpectedActionCallCount != plan.GeneratedActionExecuteCallCount)
                AddUniqueError(plan, $"Graph Effect codegen Action call count mismatch: expected={plan.ExpectedActionCallCount}, generated={plan.GeneratedActionExecuteCallCount}.");

            if (plan.ExpectedActionCallCount > 0 && plan.GeneratedActionFieldCount == 0)
                AddUniqueError(plan, "Graph Effect codegen expected Action fields, but generated no readonly action fields.");
        }

        private static void AddUniqueError(BuffGraphEffectCodegenPlan plan, string message)
        {
            if (!plan.Errors.Contains(message))
                plan.Errors.Add(message);
        }

        private static void AppendDefaultTodo(StringBuilder builder, BuffGraphEffectLifecyclePlan lifecycle)
        {
            if (lifecycle.LifecycleName == "OnApply")
            {
                builder.AppendLine("            // TODO: Apply ECS state changes here.");
                builder.AppendLine("            // Do not directly depend on View or Unity object components.");
                return;
            }

            if (lifecycle.LifecycleName == "OnTick")
            {
                builder.AppendLine("            // TODO: Implement tick logic here.");
                builder.AppendLine("            // Do not use Unity frame-time APIs as Buff runtime logic time.");
                builder.AppendLine("            // Prefer frame-based data from Buff runtime / SimulationContext where available.");
                return;
            }

            if (lifecycle.LifecycleName == "OnRemove")
            {
                builder.AppendLine("            // TODO: Clean up ECS state changes here.");
                return;
            }

            if (lifecycle.LifecycleName == "OnRefresh")
            {
                builder.AppendLine("            // TODO: Refresh ECS state here.");
                return;
            }

            builder.AppendLine("            // TODO: React to stack changes here.");
        }
    }
}
